# Use a smaller base image with CUDA support
FROM nvidia/cuda:12.3.2-runtime-ubuntu20.04
LABEL maintainer="disi-unibo-nlp"

# Set noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive

# Set working directory
WORKDIR /home/belletti/ATE-metric-calling/ATE

# Install only essential system dependencies and Python 3.9
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        python3.9 \
        python3.9-distutils \
        python3-pip \
        gcc \
        g++ \
        build-essential \
        curl \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Set CC environment variable
ENV CC=gcc
ENV PYTHONPATH=${PYTHONPATH}:/home/belletti/ATE-metric-calling

# Make Python 3.9 the default python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 && \
    update-alternatives --set python3 /usr/bin/python3.9

# Upgrade pip and install only the required Python packages
RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir fastapi uvicorn pydantic torch transformers accelerate==0.26.0 tqdm typing

RUN pip3 install --no-cache-dir peft accelerate bitsandbytes unsloth einops
# Set the Hugging Face cache directory and create it
ENV HF_HOME="/huggingface_cache"
RUN mkdir -p /huggingface_cache

COPY ATE/llm_server.py /home/belletti/ATE-metric-calling/ATE/llm_server.py

# Expose the port that FastAPI will use
EXPOSE 8000

# Run the server using uvicorn
CMD ["sh", "-c", "python3 -m uvicorn llm_server:app --host 0.0.0.0 --port ${SERVER_PORT:-8000}"]